services:
  - type: web
    name: inventario-backend
    env: node
    buildCommand: npm install && npm run build && ls -l dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 