services:
  - type: web
    name: inventario-backend
    env: node
    buildCommand: echo "=== INICIANDO BUILD ===" && npm install && echo "=== NPM INSTALL CONCLUÍDO ===" && npm run build && echo "=== BUILD CONCLUÍDO ===" && ls -l && echo "=== LISTANDO DIST ===" && ls -l dist
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 